service: philosophize-ai-api # NOTE: update this with your service name

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  profile: ${opt:aws-profile, "cmr1"}

custom:
  version: v1
  baseUrl: "api/${self:custom.version}"
  serverless-offline:
    port: 4000
    prefix: dev

functions:
  message:
    handler: handler.message
    events:
      - http:
          path: ${self:custom.baseUrl}/message
          method: get
          cors: true
