openapi: "3.0.0"
info:
  version: 0.0.1
  title: philosophize.ai api
  license:
    name: MIT
  description: philosophize
servers:
  - url: http://localhost:4000/dev/api/v1
paths:
  /templates:
    get:
      summary: List Templates
      operationId: listTemplates
      tags:
        - templates
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Templates"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new Template
      operationId: createTemplate
      tags:
        - templates
      requestBody:
        description: New Template
        required: true
        content:
          application/json:
            schema:
              properties:
                body:
                  type: string
      responses:
        200:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Templates"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /templates/{id}:
    get:
      summary: Get a single Template
      operationId: getTemplate
      tags:
        - templates
      parameters:
        - name: id
          in: path
          required: true
          description: Template ID (uuid)
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        400:
          description: Bad Request. Missing id in path?
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found. Template with given id does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update a Template
      operationId: updateTemplate
      tags:
        - templates
      parameters:
        - name: id
          in: path
          required: true
          description: Template ID (uuid)
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated Template
        required: true
        content:
          application/json:
            schema:
              properties:
                body:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        400:
          description: Bad Request. Missing id in path?
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found. Template with given id does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a Template
      operationId: deleteTemplate
      tags:
        - templates
      parameters:
        - name: id
          in: path
          required: true
          description: Template ID (uuid)
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        400:
          description: Bad Request. Missing id in path?
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found. Template with given id does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /messages:
    get:
      summary: List Messages
      operationId: listMessages
      tags:
        - messages
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Messages"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new Message
      operationId: createMessage
      description: Generate a new Message. Provide either template_id or template_body to specify or create a new Template for new Message. Omit entirely to generate from a random Template.
      tags:
        - messages
      parameters:
        - name: template_id
          in: query
          description: Template to generate Message from
          schema:
            type: string
            format: uuid
        - name: template_body
          in: query
          description: New Template body to generate Message from
          schema:
            type: string
      responses:
        200:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Messages"
        404:
          description: Given template_id not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /messages/{id}:
    get:
      summary: Get a single Message
      operationId: getMessage
      tags:
        - messages
      parameters:
        - name: id
          in: path
          required: true
          description: Message ID (uuid)
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        400:
          description: Bad Request. Missing id in path?
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found. Message with given id does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update a Message
      operationId: updateMessage
      tags:
        - messages
      parameters:
        - name: id
          in: path
          required: true
          description: Message ID (uuid)
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated Message
        required: true
        content:
          application/json:
            schema:
              properties:
                body:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        400:
          description: Bad Request. Missing id in path?
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found. Message with given id does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a Message
      operationId: deleteMessage
      tags:
        - messages
      parameters:
        - name: id
          in: path
          required: true
          description: Message ID to GET (uuid format)
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        400:
          description: Bad Request. Missing id in path?
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Not Found. Message with given id does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Template:
      required:
        - id
        - body
      properties:
        id:
          type: string
          format: uuid
        body:
          type: string
    Templates:
      type: array
      items:
        $ref: "#/components/schemas/Template"
    Message:
      required:
        - id
        - template_id
        - body
      properties:
        id:
          type: string
          format: uuid
        template_id:
          type: string
          format: uuid
        body:
          type: string
    Messages:
      type: array
      items:
        $ref: "#/components/schemas/Message"
    Error:
      required:
        - message
      properties:
        message:
          type: string
